### ISSUE TITLE
help for fix

### ISSUE THREAD

**Issue by norm-git** [hyPnOtICDo0g/rss-chan#5]
2021-08-29 16:52:21,043 - bot - INFO - Database Loaded.
2021-08-29T16:52:21.044265+00:00 app[search.1]: 2021-08-29 16:52:21,043 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
2021-08-29T16:52:21.044266+00:00 app[search.1]: Traceback (most recent call last):
2021-08-29T16:52:21.044267+00:00 app[search.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/utils/promise.py", line 57, in run
2021-08-29T16:52:21.044267+00:00 app[search.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2021-08-29T16:52:21.044268+00:00 app[search.1]:   File "/app/", line 144, in rss_load
2021-08-29T16:52:21.044268+00:00 app[search.1]:     for row in postgres_load_all():
2021-08-29T16:52:21.044268+00:00 app[search.1]: TypeError: 'Promise' object is not iterable
 
I am getting this error.
bot responds to all commands but when I command / list, bot say no subscriptions even though I have saved feed

**Comment by hyPnOtICDo0g** [comment]
@norm-git where is the bot hosted?

**Comment by norm-git** [comment]
> @norm-git where is the bot hosted?

Hroku
now is fixed. error was old ptb. Updated ptb and working.
